### ISSUE TITLE
69Shu does not work

### ISSUE THREAD

**Issue by TheFirstProgenitor** [dteviot/WebToEpub#1286]
**Describe the bug**

**To Reproduce**
1. Go to 'https://www.69shu.pro/book/46565/'
2. Click on 'WebToEpub'
3. See error

**Expected behavior**
Shows following error.👇🏼
TypeError: Cannot read properties of null (reading 'textContent')
    at ShuParser.extractTitleImpl (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/69shuParser.js:25:52)
    at ShuParser.extractTitle (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:216:26)
    at ShuParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:270:31)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:43:39)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:252:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**Smartphone (please complete the following information):**
 - Device: [Samsung A73 5G]
 - OS: [OneUI 6(Android 14)]
 - Browser [kiwi]
 - Version [Kiwi Browser 124.0.6327.2]

**Additional context**

**Comment by TheFirstProgenitor** [comment]
Sorry...
Opened from ToC page.
Works now.

**Comment by masteoo** [comment]
@dteviot hello, sorry, could you help to fix it please? Thanks 
https://github.com/dteviot/WebToEpub/issues/1142#issuecomment-2067757564
