### ISSUE TITLE
ReadFullNovel Parser Broken?

### ISSUE THREAD

**Issue by Liamcedric** [dteviot/WebToEpub#1396]
TypeError: Cannot read properties of null (reading 'getAttribute')     
at ReadNovelFullParser.fetchChapterList (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ReadNovelFullParser.js:19:54) 
at ReadNovelFullParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ReadNovelFullParser.js:15:36)     at ReadNovelFullParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:378:14)     
at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:47:24)     
at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:252:9)     
at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

Looked like there was already a parser made. At some point the Default Parser config came up but it didn't seem to love any of div selections I made. pulled the whole page up with the default parser tho.

was trying on 
https://readnovelfull.com/super-gene-v1.html#tab-chapters-title
https://readnovelfull.com/reincarnation-of-the-strongest-sword-god-v2.html#tab-chapters-title

**Comment by dteviot** [comment]
@Liamcedric 
I just tried the two URLs and they worked fine for me.
I don't know why it's not working for you.  
Looking at the code, 
1. WebToEpub looks for the a list of chapter URLs on the page that is in a &lt;ul&gt; element with a class of "list-chapter".    (Normally, this is all that is needed.)
2. If element is not found, it tries to find the novel id to request the chapters.

Based on the stack trace you supplied, It looks like 1. failed, and 2 didn't work either.  So, page layout is not what was expected.
You could open the page with the Dev tools and see if the chapters are in a &lt;ul&gt; element as previously described.

Failing that, you could try WebToEpub with a different browser.  e.g. Firefox, Edge.

For my Notes: 15 minutes work.

**Comment by Liamcedric** [comment]
@dteviot Sorry, I should have tested on Firefox before I created the issue. Works perfectly on Firefox. 

And now that I look at it, I don't think the I was on the chapter list page.. Rookie mistake, sorry for wasting your time.
