### ISSUE TITLE
Please fix the site https://novelsemperor.net/

### ISSUE THREAD

**Issue by abetestnow** [dteviot/WebToEpub#1436]
I'm currently using WebToEpub0.0.0.163.Chrome on Windows 10 and the plugin was working perfectly fine until today.

Now it's only working on novels with only one page of TOC.

If there's more than one page of TOC, (https://novelsemperor.net/series/hacker-turn-off-beauty-filter-for-female-anchors-during-live-broadcast) I get the following error:

TypeError: Failed to construct 'URL': Invalid URL
    at HttpClient.setPartitionCookies (chrome-extension://famdedgggedkniaeijhncoendapddipa/js/HttpClient.js:212:29)
    at HttpClient.wrapFetchImpl (chrome-extension://famdedgggedkniaeijhncoendapddipa/js/HttpClient.js:181:26)
    at HttpClient.wrapFetch (chrome-extension://famdedgggedkniaeijhncoendapddipa/js/HttpClient.js:155:27)
    at NovelsemperorParser.walkTocPages (chrome-extension://famdedgggedkniaeijhncoendapddipa/js/Parser.js:707:37)
    at async NovelsemperorParser.getChapterUrls (chrome-extension://famdedgggedkniaeijhncoendapddipa/js/parsers/NovelsemperorParser.js:12:17)

**Comment by dteviot** [comment]
@abetestnow 
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
*  https://novelsemperor.net/series/hacker-turn-off-beauty-filter-for-female-anchors-during-live-broadcast?page=1, chapter 1  (Has 3 ToC pages)
* https://novelsemperor.net/series/reborn-shenhao-miner?page=1, (Has 3 ToC pages)

Time taken: 33 minutes

**Comment by abetestnow** [comment]
I just tried it out and it's working perfectly.

Thank you for all your support on this great extension and fast response to bugs.

**Comment by dteviot** [comment]
@abetestnow 

Updated version (0.0.0.167) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
