### ISSUE TITLE
Problem download novel from novel18.syosetu

### ISSUE THREAD

**Issue by PHBN1964** [dteviot/WebToEpub#1441]
**Describe the bug**
When I try to download a novel from https://novel18.syosetu.com it doesn't make the epub file and this error below appears:
TypeError: Cannot read properties of null (reading 'cloneNode')
    at SyosetuParser.getInformationEpubItemChildNodes (chrome-extension://dgngpbkafocciimdoiomfhjjejieehnk/js/parsers/SyosetuParser.js:69:42)
    at SyosetuParser.populateInfoDiv (chrome-extension://dgngpbkafocciimdoiomfhjjejieehnk/js/Parser.js:355:27)
    at SyosetuParser.makeInformationEpubItem (chrome-extension://dgngpbkafocciimdoiomfhjjejieehnk/js/Parser.js:343:14)
    at SyosetuParser.webPagesToEpubItems (chrome-extension://dgngpbkafocciimdoiomfhjjejieehnk/js/Parser.js:315:33)
    at SyosetuParser.epubItemSupplier (chrome-extension://dgngpbkafocciimdoiomfhjjejieehnk/js/Parser.js:303:30)
    at packEpub (chrome-extension://dgngpbkafocciimdoiomfhjjejieehnk/js/main.js:188:37)
    at chrome-extension://dgngpbkafocciimdoiomfhjjejieehnk/js/main.js:155:20l
**To Reproduce**
1. Go to https://novel18.syosetu.com and choose a novel
2. Click on 'Pack Epub'
3. Wait till epub finish

**Expected behavior**
The novel should be downloaded

**Screenshots**
![Screenshot_20240824-114629](https://github.com/user-attachments/assets/e2dcd41d-8541-4e5d-930a-fa9aa9087183)
![Screenshot_20240824-114622](https://github.com/user-attachments/assets/92a06034-5035-4039-803c-1cf992c655c9)

**Smartphone (please complete the following information):**
 - Device: Moto G30[e.g. iPhone6]
 - OS:  Android 12[e.g. iOS8.1]
 - Browser: Kiwi Chrome[e.g. stock browser, safari]
 - Version:22 [e.g. 22]

**Additional context**

**Comment by ImLJS** [comment]
Its working properly for me. Try to turn on desktop mode and use the extension

**Comment by dteviot** [comment]
@PHBN1964 
I confirm, it's also working for me with desktop version of Chrome.
Please close this issue if setting your browser to desktop mode works.  Or let us know if it does not.
