### ISSUE TITLE
kemono.su Pack EPUB fails

### ISSUE THREAD

**Issue by xypha** [dteviot/WebToEpub#1575]
**Describe the bug**
Pack EPUB fails due to following error -  

`Could not find content element for web page 'https://kemono.su/patreon/user/74491564/post/110039760'. fetchWebPageContent/<@moz-extension://687e031b-7c4d-4d1a-95c6-b98a819310a2/js/Parser.js:519:23`

**To Reproduce**
1. Go to [Kemono](https://kemono.su/patreon/user/74491564)
2. Click on WebToEpub toolbar icon and wait for chapters to load
3. Click on 'Edit Chapter URLs' and enter the following -
```
<a href="https://kemono.su/patreon/user/74491564/post/110039760">[Young Master Xian]—❈—18:: The Plot Thickens</a>
<a href="https://kemono.su/patreon/user/74491564/post/110390204">[Young Master Xian]—❈—18.1:: Interlude:: Perspectives</a>
<a href="https://kemono.su/patreon/user/74491564/post/110631098">[Young Master Xian]—❈—19:: Tea and Conversation</a>
<a href="https://kemono.su/patreon/user/74491564/post/111160323">[Young Master Xian]—❈—20:: Shopping</a>
<a href="https://kemono.su/patreon/user/74491564/post/111622345">[Young Master Xian]—❈—21:: unnamed</a>
<a href="https://kemono.su/patreon/user/74491564/post/112109206">[Young Master Xian]—❈—22:: unnamed</a>
<a href="https://kemono.su/patreon/user/74491564/post/112297089">[Young Master Xian]—❈—22.5:: unnamed</a>
<a href="https://kemono.su/patreon/user/74491564/post/113688810">[Young Master Xian]—❈—23:: unnamed</a>
<a href="https://kemono.su/patreon/user/74491564/post/114514446">[Young Master Xian]—❈—24:: unnamed</a>
<a href="https://kemono.su/patreon/user/74491564/post/114865779">[Young Master Xian]—❈—25:: Combat &amp; Accountants</a>
<a href="https://kemono.su/patreon/user/74491564/post/115414253">[Young Master Xian]—❈—26:: "Glory of the Sun"</a>
<a href="https://kemono.su/patreon/user/74491564/post/115635167">[Young Master Xian]—❈—26.1:: Interlude</a>
<a href="https://kemono.su/patreon/user/74491564/post/115940071">[Young Master Xian]—❈—27:: "You Dare"</a>
<a href="https://kemono.su/patreon/user/74491564/post/116084142">[Young Master Xian]—❈—Artwork:: Tao Jin</a>
<a href="https://kemono.su/patreon/user/74491564/post/116131163">[Young Master Xian]—❈—28:: Meet the Mengs</a>
<a href="https://kemono.su/patreon/user/74491564/post/116438566">[Young Master Xian]—❈—29:: Tea Time</a>
```
5. Click on 'Apply changes' and then click on 'Pack EPUB' to see error.

**Expected behavior**
Pack EPUB succeeds

**Screenshots**
![2024-11-24 @ 05：06：55](https://github.com/user-attachments/assets/9dc50688-80a4-4daf-8e6b-7ce64db0e51c)

**Desktop (please complete the following information):**
 - OS: Windows 23H2 22631.4460
 - Browser: Firefox 132.0.2 (64-bit)
 - WebToEpub Version 1.0.1.0 (Last Updated 10 November 2024)

**Additional context**
The site may have changed it's url scheme.. maybe.. not sure..
I say this because it's favourites page moved from `https://kemono.su/favorites` to `https://kemono.su/account/favorites/artists` (this happened once a while ago, but was reverted back, but I didnt notice any problems with WebToEpub then).

Similar error msg is show when generating epub for [this](https://kemono.su/patreon/user/27394282) user as well;
and only the chapters on page 1 is loaded. Chapters from page 2-10 or more are missing.

![2024-11-24 @ 05：20：41](https://github.com/user-attachments/assets/bfbb6bf1-98f3-47c0-9aa4-b5fa7f6b785e)
![2024-11-24 @ 05：19：58](https://github.com/user-attachments/assets/e49bbe37-dadd-4939-b886-086e9cd9922c)

**Comment by ImLJS** [comment]
@xypha  I checked it from my end but the extension is working properly for me. The Edit urls as well as the account you mentioned did not raise any error.

**Comment by xypha** [comment]
it's working for me as well now. don't know why, coz I changed nothing.  
Also, favourites page has (again) reverted to `https://kemono.su/favorites`. Maybe other changes were reverted too.  :shrug:
sorry for the trouble.

**Comment by grenskul** [comment]
Not working for me either . It finds all the chapters and then when I try to make the epub I get this .
![image](https://github.com/user-attachments/assets/d4dae639-e72d-484a-9582-f19b06f7965b)

**Comment by PolarisFx** [comment]
kemono has changed the front-end code. They're loading posts in chunks asynchronously now.

**Comment by akisok** [comment]
> kemono has changed the front-end code. They're loading posts in chunks asynchronously now.

so no fix for that ?

**Comment by ImLJS** [comment]
@dteviot I need your help in this. Now kemono is getting data from api calls, I was able to get the correct chapter count, chapter url and title

```
async getChapterUrls(dom) {
        const userId = new URL(dom.baseURI).pathname.split("/").pop();
        const baseUrl = `https://kemono.su/api/v1/patreon/user/${userId}/posts-legacy`;
        let offset = 0;
        const limit = 50;
        let results = [];
        let hasMore = true;

        while (hasMore) {
            const apiUrl = `${baseUrl}?o=${offset}`;
            const response = await fetch(apiUrl);
            const data = await response.json();
            results = results.concat(data.results);
            offset += limit;
            hasMore = data.results.length === limit;
        }
        return results.map(post => ({
            sourceUrl: `https://kemono.su/api/v1/patreon/user/${userId}/post/${post.id}`,
            title: post.title
        }));
    }
```

But now the problem is getting this error. 

![image](https://github.com/user-attachments/assets/e5314802-be56-4251-a6d4-2368807df8b2)

By commenting out preprocessRawDom. Got a new Error.

![image](https://github.com/user-attachments/assets/52081ca2-3fc4-4343-8972-18ad57e40a02)

I know, it is due to removeUnusedElementsToReduceMemoryConsumption but I have no clue how to solve this. Can you look into it.

**Comment by ImLJS** [comment]
@dteviot I need your help in this. Now kemono is getting data from api calls, I was able to get the correct chapter count, chapter url and title

```
async getChapterUrls(dom) {
        const userId = new URL(dom.baseURI).pathname.split("/").pop();
        const baseUrl = `https://kemono.su/api/v1/patreon/user/${userId}/posts-legacy`;
        let offset = 0;
        const limit = 50;
        let results = [];
        let hasMore = true;

        while (hasMore) {
            const apiUrl = `${baseUrl}?o=${offset}`;
            const response = await fetch(apiUrl);
            const data = await response.json();
            results = results.concat(data.results);
            offset += limit;
            hasMore = data.results.length === limit;
        }
        return results.map(post => ({
            sourceUrl: `https://kemono.su/api/v1/patreon/user/${userId}/post/${post.id}`,
            title: post.title
        }));
    }

    async fetchChapter(url) {
        const response = await fetch(url);
        const data = await response.json();
        const content = data.post.content;
        const doc = Parser.makeEmptyDocForContent(url);
        doc.content.innerHTML = content;
        return doc;
    }
```

But now the problem is getting this error. 

![image](https://github.com/user-attachments/assets/52081ca2-3fc4-4343-8972-18ad57e40a02)

I have no clue how to solve this. Can you look into it.

**Comment by lll000111** [comment]
Version 1.0.1.0

Calling it on an author page works, sure, but it only finds the chapters listed on the first page.

When actually running it it only loads a single URL/chapter. The epub it offers to save is empty and broken.

Nobody posted the FULL error yet? With the stacktrace.

```
rror: Could not find content element for web page 'https://kemono.su/patreon/user/34232701/post/113056507'.
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:519:23
    at async Promise.all (index 0)
    at async KemonopartyParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:484:17)
```

**Another new issue** with text chapters on kemono now is the incredibly stupid and unfathomable decision to wrap the chapter's HTML inside a PRE tag. WebToEpub should not include that tag, only the actual chapter HTML.

**Comment by akisok** [comment]
i fixed it for myself but you will need to manually do that you will need to change the parser of kemono to code given below and then reinstall it to your browser manually then you can create epubs easily

code given by [DawnBreaker0013](https://github.com/DawnBreaker0013)-:

"use strict";

parserFactory.register("kemono.su", () => new KemonopartyParser());

class KemonopartyParser extends Parser{
    constructor() {
        super();
    }

    async getChapterUrls(dom, chapterUrlsUI) {
        return (await this.getChapterUrlsFromMultipleTocPages(dom,
            this.extractPartialChapterList,
            this.getUrlsOfTocPages,
            chapterUrlsUI
        )).reverse();
    };

    async getChapterUrlsFromMultipleTocPages(dom, extractPartialChapterList, getUrlsOfTocPages, chapterUrlsUI)  {
        let urlsOfTocPages = getUrlsOfTocPages(dom);
        return await this.getChaptersFromAllTocPages([], extractPartialChapterList, urlsOfTocPages, chapterUrlsUI);
    }

    async fetchChapter(url) {
        return (new TextDecoder().decode((await HttpClient.wrapFetch(url)).arrayBuffer));
    }

    async getChaptersFromAllTocPages(chapters, extractPartialChapterList, urlsOfTocPages, chapterUrlsUI)  {
        if (0 < chapters.length) {
            chapterUrlsUI.showTocProgress(chapters);
        }
        for(let url of urlsOfTocPages) {
            await this.rateLimitDelay();
            let json_string = await this.fetchChapter(url);
            let partialList = extractPartialChapterList(json_string);
            chapterUrlsUI.showTocProgress(partialList);
            chapters = chapters.concat(partialList);
        }
        return chapters;
    }

    async fetchWebPageContent(webPage) {
        let that = this;
        ChapterUrlsUI.showDownloadState(webPage.row, ChapterUrlsUI.DOWNLOAD_STATE_SLEEPING);
        await this.rateLimitDelay();
        ChapterUrlsUI.showDownloadState(webPage.row, ChapterUrlsUI.DOWNLOAD_STATE_DOWNLOADING);
        let pageParser = webPage.parser;
        return pageParser.fetchChapter(webPage.sourceUrl).then(function (json_string) {
            delete webPage.error;
            webPage.rawDom = Document.parseHTMLUnsafe(`<html><script>${json_string}</script></html>`);
            console.log(webPage);
            let content = pageParser.findContent(webPage.rawDom);
            if (content == null) {
                let errorMsg = chrome.i18n.getMessage("errorContentNotFound", [webPage.sourceUrl]);
                throw new Error(errorMsg);
            }
            return pageParser.fetchImagesUsedInDocument(content, webPage);
        }).catch(function (error) {
            if (that.userPreferences.skipChaptersThatFailFetch.value) {
                ErrorLog.log(error);
                webPage.error = error;
            } else {
                webPage.isIncludeable = false;
                throw error;
            }
        }); 
    }

    findCoverImageUrl(dom) {
        let cover = dom.querySelector(".user-header__avatar img");
        return cover.src ?? null;
    }


    getUrlsOfTocPages(dom) {
        let urls = [];
        let paginator = dom.querySelector("div.paginator menu");
        if (paginator === null) {
            return urls;
        }
        let pages = [...paginator.querySelectorAll("a:not(.next)")];
        // add /api/v1/ right after the domain name
        pages[pages.length - 1].href = pages[pages.length - 1].href.replace("https://kemono.su", "https://kemono.su/api/v1");
        // add /posts-legacy right before the query string
        pages[pages.length - 1].href = pages[pages.length - 1].href.replace("?", "/posts-legacy?");
        let url = new URL(pages[pages.length - 1]);
        let lastPageOffset = url.searchParams.get("o");
        for(let i = 0; i <= lastPageOffset; i += 50) {
            url.searchParams.set("o", i);
            urls.push(url.href);
        }
        console.log(urls);
        return urls;
    }
    
    extractPartialChapterList(json_string) {
        // get href from the dom, not the url of the page
        try {
            let data = JSON.parse(json_string);
            let authorid = data.props.id;
            let ids = data.results.map(result => result.id);
            let titles = data.results.map(result => result.title);
            let urls = ids.map(id => `https://kemono.su/api/v1/patreon/user/${authorid}/post/${id}`);
            return urls.map((url, i) => ({
                sourceUrl: url,
                title: titles[i]
            }));
        } catch (e) {
            console.error(e);
            return [];
        }
    }
    
    findContent(dom) {
        console.log(dom);
        //the text of the chapter is always in .post__content, but if there is no chapter(e.g. only files), return .post__body instead of throwing an error
        // return dom.querySelector(".post__content") ?? dom.querySelector(".post__body");
        let data = JSON.parse(dom.querySelector("script").innerHTML);
        // create a dom element from data.post.content;
        let content_dom = document.createElement("div");
        content_dom.innerHTML = data.post.content;
        return content_dom;
    }

    copyImagesIntoContent(dom) {
        let content = this.findContent(dom);
        let images = [...dom.querySelectorAll("div.post__files div.post__thumbnail figure a img")];
        for(let img of images) {
            content.append(img);
        }
    }

    extractTitleImpl(dom) {
        return dom.querySelector("h1");
    }

    findChapterTitle(dom) {
        return JSON.parse(dom.querySelector("script").innerHTML).post.title;
    }
}

**Comment by ImLJS** [comment]
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

**Comment by xypha** [comment]
@ImLJS Tried https://kemono.su/patreon/user/6869809
using **WebToEpub1.0.1.9.Firefox** a few days ago and it worked well.
Thank you!

**Comment by DawnBreaker0013** [comment]
Hi I know I added the code but there is a problem with Document.parseHTMLunsafe as some browsers do not support it. Here is a screenshot from kiwi browser (Android) . 

![Screenshot_20241215-165334](https://github.com/user-attachments/assets/752d1b4c-69b0-45a7-93e0-bf0785c984b0)

**Comment by dteviot** [comment]
@DawnBreaker0013 

I have doubts that Chrome or Firefox stores will allow an extension that uses that call.

Looking at the code, could probably use
HttpClient.fetchJson() to get the JSON, and then use the code in findContent() to extract the JSON we're interested in and build the document.  No need to convert to a DOM and then parse the JSON again.

Something like:

```javascript
    async fetchChapter(url) {
        let json = (await HttpClient.fetchJson(url)).json;
        return this.buildChapter(json, url);
    }

    buildChapter(json, url) {
        let newDoc = Parser.makeEmptyDocForContent(url);
        let content = new DOMParser().parseFromString(json.post.content, "text/html");
        for(let n of [...content.body.childNodes]) {
            newDoc.content.appendChild(n);
        }
        return newDoc.dom;
    }
```

Have a look at https://github.com/dteviot/WebToEpub/blob/ExperimentalTabMode/plugin/js/parsers/CrimsontranslationsParser.js

**Comment by lll000111** [comment]
> Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build.

Inline images are not included.

Example page, this author adds "Status" screens as image, unfortunately: [https://kemono.su/patreon/user/4125593/post/116695127](https://kemono.su/patreon/user/4125593/post/116695127)

Inside the HTML the image looks like this:

```html
<div><img src="../Images/0001_76fc41db9cd5e7e455c0ca2e54e67c863a5ae5fbc3bb25c2308aa6458b19c478.webp" alt="" /><!--  chrome-extension://olkdakjghpkikaimakakhphbipghpenb/76/fc/76fc41db9cd5e7e455c0ca2e54e67c863a5ae5fbc3bb25c2308aa6458b19c478.webp  --></div>
```

The cover webp image is in teh epub - but the two inline webp images are size 0.

Epub creaton ended with these errors:

```
Error: Fetch of image 'chrome-extension://olkdakjghpkikaimakakhphbipghpenb/76/fc/76fc41db9cd5e7e455c0ca2e54e67c863a5ae5fbc3bb25c2308aa6458b19c478.webp' for page 'https://kemono.su/api/v1/patreon/user/4125593/post/116695127' failed with network error Failed to fetch.     at FetchImageErrorHandler.onFetchError (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/HttpClient.js:28:31)     at HttpClient.wrapFetchImpl (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/HttpClient.js:201:45)     at async ImageCollector.fetchImage (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/ImageCollector.js:335:23)     at async ImageCollector.fetchImages (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/ImageCollector.js:108:17)     at async Promise.all (index 0)     at async KemonopartyParser.fetchWebPages (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/Parser.js:484:17)  Error: Fetch of image 'chrome-extension://olkdakjghpkikaimakakhphbipghpenb/ee/09/ee098954ab1572943a9dd39a97c05e97a2cbb2f10d015232a9cc731b20317c29.webp' for page 'https://kemono.su/api/v1/patreon/user/4125593/post/116695127' failed with network error Failed to fetch.     at FetchImageErrorHandler.onFetchError (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/HttpClient.js:28:31)     at HttpClient.wrapFetchImpl (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/HttpClient.js:201:45)     at async ImageCollector.fetchImage (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/ImageCollector.js:335:23)     at async ImageCollector.fetchImages (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/ImageCollector.js:108:17)     at async Promise.all (index 0)     at async KemonopartyParser.fetchWebPages (chrome-extension://olkdakjghpkikaimakakhphbipghpenb/js/Parser.js:484:17)  Warning: image file 'Images/0000.webp' is in webp format.  Your epub viewer may not be able to render it.
```

**Comment by dteviot** [comment]
@DawnBreaker0013

Commit that removes call to Document.parseHTMLUnsafe(), plus some code refactor.

@lll000111 bonus, now seems to be working for inline images.

Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://kemono.su/patreon/user/6869809, chapters 1 to 4
* https://kemono.su/patreon/user/4125593, chapter 334  (inline images)

Notes
Time taken: (me) 82 minutes.  Other people, is unknown.

**Comment by dteviot** [comment]
More work required.

https://kemono.su/patreon/user/74491564, has items where there are images in the "files" section.  e.g. 
https://kemono.su/patreon/user/74491564/post/117551234

**Comment by dteviot** [comment]
And... fixed.

Tested with:
* https://kemono.su/patreon/user/74491564/post/117551234

Notes
Time taken: (Total, me) 152 minutes. Other people, is unknown.

**Comment by xypha** [comment]
Tested WebToEpub1.0.1.22.Firefox.zip
Works well

**Comment by dteviot** [comment]
@xypha 
@lll000111 
@DawnBreaker0013 
@akisok 
@grenskul 
@PolarisFx 

Updated version (1.0.2.0) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours (typical) to 21 days.
