### ISSUE TITLE
wuxiabox.com cant fetch. (the site changed constantly readwn.com et cetera)

### ISSUE THREAD

**Issue by Veaxale** [dteviot/WebToEpub#1584]
Error: WARNING: Site 'www.wuxiabox.com' has sent an Access Denied (403) error.
You may need to logon to site, or browse site normally
until you get a Cloudflare "Are you a human" page or satisfy some other CAPTCHA
before WebToEpub can continue.
Fetch of URL 'https://www.wuxiabox.com/e/extend/fy.php?page=1&wjm=anime-a-stranger-who-started-from-a-wrong-place' failed with network error 403. This is an intermittent error. If you retry in a few minutes, it may succeed.
    at FetchErrorHandler.promptUserForRetry (chrome-extension://kfdmfepcmpnhpihmbbjodccfcghcdbjb/js/HttpClient.js:57:19)
    at FetchErrorHandler.onResponseError (chrome-extension://kfdmfepcmpnhpihmbbjodccfcghcdbjb/js/HttpClient.js:48:25)
    at HttpClient.checkResponseAndGetData (chrome-extension://kfdmfepcmpnhpihmbbjodccfcghcdbjb/js/HttpClient.js:207:45)
    at HttpClient.wrapFetchImpl (chrome-extension://kfdmfepcmpnhpihmbbjodccfcghcdbjb/js/HttpClient.js:197:31)
    at async ReadwnParser.getChaptersFromAllTocPages (chrome-extension://kfdmfepcmpnhpihmbbjodccfcghcdbjb/js/Parser.js:706:27)
    at async ReadwnParser.getChapterUrlsFromMultipleTocPages (chrome-extension://kfdmfepcmpnhpihmbbjodccfcghcdbjb/js/Parser.js:676:16problem.

 - Device: Infinix zero 5g
 - OS: Android
 - Kiwibrowser latest
 -
site always the address to a new one in a week or a few days.

**Comment by dteviot** [comment]
@Veaxale 

Your problem sounds like a known issue with kiwibrowser's handling of Cloudflare cookies.  https://github.com/dteviot/WebToEpub/issues/1326

Suggested workaround is to use the Firefox for Android browser. https://github.com/dteviot/WebToEpub/issues/1551

**Comment by gamebeaker** [comment]
Kiwi browser is no longer supported.
