### ISSUE TITLE
Syosetu

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#1607]
**Describe the bug**
Can not parsing

TypeError: Cannot read properties of null (reading 'href')
    at SyosetuParser.fetchAndAttachInfoPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/SyosetuParser.js:22:81)
    at SyosetuParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/SyosetuParser.js:13:20)
    at SyosetuParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:378:14)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:47:24)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:252:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**Smartphone (please complete the following information):**
 - Device: [Android 12; TECNO LF7n Build/SP1A.210812.016]
 - OS: [HiOs 8.6.0]
 - Browser [kiwi]
 - Version [112.0.5615.137]

**Comment by dteviot** [comment]
@3dycosmo 

Please provide URL

**Comment by ImmortalDreamer** [comment]
@dteviot Latest version from the web store seems to work both on PC and Kiwi browser on Android.
@3dycosmo Which version of the WebToEpub extension are you using? Try updating extension to the latest version and try again.

**Comment by 3dycosmo** [comment]
@dteviot @ImmortalDreamer Thanks a lot, bro! I hadn't updated the extension, but it's working now. The issue earlier was that Kiwi somehow didn't update automatically on the playstore. Because of that, the extension also didn't update, as the older version wasn't compatible with the Chrome Web Store

**Comment by dteviot** [comment]
@3dycosmo 
Thanks for the update

@ImmortalDreamer 
Thanks for the assist.
