### ISSUE TITLE
babelnovel changed again :/

### ISSUE THREAD

**Issue by zanson** [dteviot/WebToEpub#295]
Looks like babel changed something again:

```
TypeError: Cannot read property 'name' of undefined
    at BabelChainParser.extractTitleImpl (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/BabelChainParser.js:46:39)
    at BabelChainParser.extractTitle (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:175:26)
    at BabelChainParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:218:31)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:42:39)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:206:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)
```

**Comment by dteviot** [comment]
@zanson 
I just tried https://babelnovel.com/books/fanatic-divine-cultivator and
https://babelnovel.com/books/ultimate-martial-divine-king.  They seem to work fine.  What URL did you have problems with?

**Comment by zanson** [comment]
It was https://babelnovel.com/books/nine-star-hegemon-body-arts/ but that seems to be working today, so guess they changed it back.
