### ISSUE TITLE
[ERROR] Getting Images Novelplanet "click arrow images"

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#299]
#280 ERROR getiing images from novel with this set;

> Click the arrows to see the illustrations
> These illustrations are from the inside front cover

<a href="https://novelplanet.com/Novel/Is-it-Tough-Being-a-Friend/v4-illustrations?id=740090">Is it Tough Being a Friend? Volume 4 illustrations</a>

```
Error: Fetch of image 'https://images2-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&gadget=a&no_expand=1&resize_h=0&rewriteMime=image%2F*&url=https%3a%2f%2fi0.wp.com%2f2slow2latemtl.icu%2fwp-content%2fuploads%2f2019%2f10%2fi-0001_01.jpg%3fresize%3d825%252C1180%26ssl%3d1' for page 'https://novelplanet.com/Novel/Is-it-Tough-Being-a-Friend/v4-illustrations?id=740090' failed with network error Failed to fetch.
    at FetchImageErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:24:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:155:45
    at async Promise.all (index 0)
```

**Comment by dteviot** [comment]
@3dycosmo 
As I said before in https://github.com/dteviot/WebToEpub/issues/298, NovelPlanet is an exaggerator site, this particular story seems to be copied from https://2slow2latemtl.icu/is-it-tough-being-a-friend-toc/

In the process of coping, image tags were changed from
```html
<img class="alignnone size-full wp-image-3515" src="https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?resize=825%2C595&#038;ssl=1" alt="i-0002-0003_01" width="825" height="595" srcset="https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?w=1600&amp;ssl=1 1600w, https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?resize=300%2C216&amp;ssl=1 300w, https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?resize=768%2C554&amp;ssl=1 768w, https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?resize=1024%2C739&amp;ssl=1 1024w" sizes="(max-width: 825px) 100vw, 825px" data-recalc-dims="1" />

to 
```html
<img class="alignnone size-full wp-image-3515" src="https://images2-focus-opensocial.googleusercontent.com/gadgets/proxy?container=focus&gadget=a&no_expand=1&resize_h=0&rewriteMime=image%2F*&url=https%3a%2f%2fi0.wp.com%2f2slow2latemtl.icu%2fwp-content%2fuploads%2f2019%2f10%2fi-0002-0003_01.jpg%3fresize%3d825%252C595%26ssl%3d1" alt="i-0002-0003_01" width="825" height="595" srcset="https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?w=1600&amp;ssl=1 1600w, https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?resize=300%2C216&amp;ssl=1 300w, https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?resize=768%2C554&amp;ssl=1 768w, https://i0.wp.com/2slow2latemtl.icu/wp-content/uploads/2019/10/i-0002-0003_01.jpg?resize=1024%2C739&amp;ssl=1 1024w" sizes="(max-width: 825px) 100vw, 825px" data-recalc-dims="1">

Trying to follow the new src values doesn't work.  (I suspect it's again some sort of lazy loading)  However, if you go to the original source, those image links work (although it does appear some of the full size images are damaged.

**Comment by dteviot** [comment]
I'm going to call this solved.  @3dycosmo  If there's still a problem, add a comment with details to this and I'll reopen
