### ISSUE TITLE
Babelnovel doesn't work anymore i think?

### ISSUE THREAD

**Issue by God-Jiexi** [dteviot/WebToEpub#310]
hi, 

I'm getting this error when i try to fetch any of the free books released.
Book: https://babelnovel.com/books/supreme-taoism-master

Error: Fetch of URL 'https://babelnovel.comundefined' failed with network error Failed to fetch.
 at FetchErrorHandler.onFetchError (chrome-extension://dfipcjojkpjbahnnbcdokbbamkkdahbj/js/HttpClient.js:24:31)
 at chrome-extension://dfipcjojkpjbahnnbcdokbbamkkdahbj/js/HttpClient.js:156:45
at async Function.fetchCcsFilter (chrome-extension://dfipcjojkpjbahnnbcdokbbamkkdahbj/js/parsers/BabelChainParser.js:107:19)
at async BabelChainParser.fetchChapter (chrome-extension://dfipcjojkpjbahnnbcdokbbamkkdahbj/js/parsers/BabelChainParser.js:96:25)
 at async Promise.all (index 0).

version: 0.0.0.94 and 0.0.0.93

**Comment by dteviot** [comment]
@God-Jiexi 
Site has changed format again.
I've updated WebToEpub with the changes and submitted new version (0.0.0.94) to Chrome and Mozilla stores.  Firefox version is available for download from here: https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/
Goggle has decided to audit WebToEpub, so the new version won't be available from Chrome until that is done.  Likely to be days.  So, you can check the web store for available version until it's updated.  Or use the Firefox version.
