### ISSUE TITLE
https://babelnovel.com/books/naruto-one-click-999

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#359]
Please help -

TypeError: Cannot read property 'bookDetailStore' of undefined
    at BabelChainParser.getBookEntity (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/BabelChainParser.js:21:22)
    at BabelChainParser.extractTitleImpl (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/BabelChainParser.js:42:21)
    at BabelChainParser.extractTitle (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:185:26)
    at BabelChainParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:228:31)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:42:39)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:211:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**Comment by dteviot** [comment]
@Finks82
Updated version (0.0.0.114) has been submitted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be (at least) a few days to finish review (I got a warning it may take several weeks this time.).
