### ISSUE TITLE
Error for lightnovelworld.com: Cannot read property 'textContent' of null

### ISSUE THREAD

**Issue by Ryvallsaarina** [dteviot/WebToEpub#367]
TypeError: Cannot read property 'textContent' of null
    at linkToChapterIfo (chrome-extension://akpmekgbdklpibgfikhjckdffgcgblem/js/parsers/LightNovelWorldParser.js:31:59)
    at Array.map (<anonymous>)
    at Function.extractPartialChapterList (chrome-extension://akpmekgbdklpibgfikhjckdffgcgblem/js/parsers/LightNovelWorldParser.js:26:14)
    at LightNovelWorldParser.getChapterUrls (chrome-extension://akpmekgbdklpibgfikhjckdffgcgblem/js/parsers/LightNovelWorldParser.js:15:54)
    at LightNovelWorldParser.onLoadFirstPage (chrome-extension://akpmekgbdklpibgfikhjckdffgcgblem/js/Parser.js:332:14)
    at processInitialHtml (chrome-extension://akpmekgbdklpibgfikhjckdffgcgblem/js/main.js:46:24)
    at populateControlsWithDom (chrome-extension://akpmekgbdklpibgfikhjckdffgcgblem/js/main.js:211:9)
    at onMessageListener (chrome-extension://akpmekgbdklpibgfikhjckdffgcgblem/js/main.js:16:13)

When i tried, it could only open url by chapter one by one and not the whole.
Can you fix it please.

**Comment by dteviot** [comment]
@Ryvallsaarina Thank you for bringing this to my attention.
Updated version (0.0.0.116) has been submitted to Firefox store and is available.
I'm currently unable to submit updated version to Chrome store at moment as previous version is still being reviewed.  I'll update the Chrome store as soon as I can.
