### ISSUE TITLE
https://babelnovel.com/books/naruto-the-strongest-deceiving-system/chapters

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#427]
need support https://babelnovel.com/books/naruto-the-strongest-deceiving-system/chapters 

thx

**Comment by Finks82** [comment]
TypeError: Cannot read property 'href' of null
    at BabelChainParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/BabelChainParser.js:13:70)
    at BabelChainParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:357:14)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:46:24)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:214:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**Comment by dteviot** [comment]
@Finks82 
Site has changed it's layout yet again.  I **think** I've got it fixed.  However, due to limit of 2 chapters per day, it's hard to be sure.
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by dteviot** [comment]
@Finks82
Updated version 0.0.0.124 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
