### ISSUE TITLE
Unit tests don't work under chrome

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#483]
See: https://github.com/dteviot/WebToEpub/pull/478#issuecomment-788994703

**Comment by dteviot** [comment]
@gamebeaker
See: https://github.com/dteviot/WebToEpub/pull/478#issuecomment-788994703
Basically, when running unit tests under Chrome, get a number tests that fail with an error like:
> Died on test #1     at file:///E:/ToBackup/Projects/GitHub/WebToEpub/unitTest/UtestArchiveOfOurOwnParser.js:31:7: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///E:/ToBackup/Projects/GitHub/WebToEpub/testdata/DredC1.html'.@ 1 ms
Source: 	
Error: Failed to execute 'send' on 'XMLHttpRequest': Failed to load 'file:///E:/ToBackup/Projects/GitHub/WebToEpub/testdata/DredC1.html'.
    at syncLoadArchiveOfOurOwnSampleDoc (file:///E:/ToBackup/Projects/GitHub/WebToEpub/unitTest/UtestArchiveOfOurOwnParser.js:25:9)
    at Object.<anonymous> (file:///E:/ToBackup/Projects/GitHub/WebToEpub/unitTest/UtestArchiveOfOurOwnParser.js:33:38)

This is due to not starting Chrome with command line argument --allow-file-access-from-files
i.e.
1. Close all copies of Chrome.
2. Open a command prompt
3. Go to directory holding Chrome.exe
4. Type in command "chrome.exe --allow-file-access-from-files" without the quotes.
