### ISSUE TITLE
Foxaholic error

### ISSUE THREAD

**Issue by JasCU100** [dteviot/WebToEpub#498]
**Describe the bug**
I get a Type Error when I try to make an epub from Foxaholic. It does not output any epub. I'm using Chrome. 

Here is what it says:
TypeError: Cannot read property 'textContent' of null
    at FoxaholicParser.findChapterTitle (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/FoxaholicParser.js:22:60)
    at FoxaholicParser.addTitleToContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:108:26)
    at FoxaholicParser.convertRawDomToContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:91:14)
    at FoxaholicParser.webPageToEpubItems (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:178:28)
    at DefaultParser.webPagesToEpubItems (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:312:34)
    at DefaultParser.epubItemSupplier (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:294:30)
    at packEpub (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:171:37)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:144:20

**To Reproduce**
Here is the link: 
<a href="https://foxaholic.com/i-really-am-a-slag-shou-chapter-11-1/">Chapter 11 Only ghosts would like you (1)</a>

**Expected behavior**
I expected it to output normally.

**Comment by dteviot** [comment]
@JasCU100 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, that chapter seems to be something of a special case.  I'm not sure how many more there are like that.

**Comment by dteviot** [comment]
@JasCU100
Updated version (0.0.0.130) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
