### ISSUE TITLE
ranobes.net

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#554]
Hello

When I try to get a novel like [this](https://ranobes.net/up/against-heavens-will/), i have an error 
```

TypeError: Cannot read property 'querySelectorAll' of null
    at Object.removeChildElementsMatchingCss (chrome-extension://gnkphobpboedagfgldjffonelbfpdebf/js/Util.js:184:37)
    at RanobesParser.extractTitleImpl (chrome-extension://gnkphobpboedagfgldjffonelbfpdebf/js/parsers/RanobesParser.js:52:14)
    at RanobesParser.extractTitle (chrome-extension://gnkphobpboedagfgldjffonelbfpdebf/js/Parser.js:208:26)
    at RanobesParser.getEpubMetaInfo (chrome-extension://gnkphobpboedagfgldjffonelbfpdebf/js/Parser.js:262:31)
    at processInitialHtml (chrome-extension://gnkphobpboedagfgldjffonelbfpdebf/js/main.js:42:39)
    at populateControlsWithDom (chrome-extension://gnkphobpboedagfgldjffonelbfpdebf/js/main.js:221:9)
    at onMessageListener (chrome-extension://gnkphobpboedagfgldjffonelbfpdebf/js/main.js:16:13)
```

Best regards

**Comment by Flwk** [comment]
Oh Sorry, i have found the problem. 

I should have used this link instead : https://ranobes.net/novels/589677-against-heavens-will-v18229.html
