### ISSUE TITLE
https://mtlreader.com/

### ISSUE THREAD

**Issue by Ndonkz** [dteviot/WebToEpub#582]
###ToC
https://mtlreader.com/novels/194

###Error
TypeError: Failed to execute 'appendChild' on 'Node': parameter 1 is not of type 'Node'.
    at MtlreaderParser.fetchChapter (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MtlreaderParser.js:35:24)
    at async Promise.all (index 7)
    at async MtlreaderParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17)

###Why add this
Currently the only one on Internet who really mtl Korean novels and its novel not copy paste other sites, no sites had similar novel like "Reverse Villain" "Lightning Degree" etc
Thx a lot, hope your consideration

**Comment by dteviot** [comment]
Closing as duplicate of https://github.com/dteviot/WebToEpub/issues/587
