### ISSUE TITLE
Boxnovel.com 

### ISSUE THREAD

**Issue by dharen123** [dteviot/WebToEpub#586]
**Describe the bug**
TypeError: Cannot read property 'querySelectorAll' of null
    at BoxnovelParser.extractTitleImpl (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/BoxnovelParser.js:22:32)
    at BoxnovelParser.extractTitle (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:208:26)
    at BoxnovelParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:262:31)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:42:39)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:222:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**To Reproduce**
1. Go to 'https://boxnovel.com/novel/xianxia-my-junior-sisters-are-freaks/'
2. Click on 'https://boxnovel.com'

**Expected behavior**

**Screenshots**
![12](https://user-images.githubusercontent.com/90084044/132084788-5dc82ab8-2b45-4f73-b635-d6e8723a3854.jpg)

**Desktop (please complete the following information):**
 - OS: Windows 8.1
 - Browser: Google Chrome
 - Version:  92.0.4515.131

**Comment by dteviot** [comment]
@dharen123
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by DicerX** [comment]
Getting the same issue here will try a different version as noted.

**Comment by dteviot** [comment]
@DicerX @dharen123
Updated version (0.0.0.138) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
