### ISSUE TITLE
the site readlightnovel acting up again on webtoepub

### ISSUE THREAD

**Issue by jillybeans** [dteviot/WebToEpub#596]
this happends now on the site, and no epubs are made for this page https://www.readlightnovel.me/only-i-am-a-necromancer
the previous update works for that other novel, but this happends for this one

TypeError: Cannot read properties of null (reading 'nextElementSibling')
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ReadLightNovelParser.js:148:72
    at ReadLightNovelParser.addSiblingIfMatches (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ReadLightNovelParser.js:158:23)
    at ReadLightNovelParser.addNextSiblingIfMatches (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ReadLightNovelParser.js:148:21)
    at ReadLightNovelParser.removeUnwantedElementsFromContentElement (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/ReadLightNovelParser.js:131:18)
    at ReadLightNovelParser.convertRawDomToContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:90:14)
    at ReadLightNovelParser.webPageToEpubItems (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:178:28)
    at ReadLightNovelParser.webPagesToEpubItems (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:312:34)
    at ReadLightNovelParser.epubItemSupplier (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:294:30)
    at packEpub (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:172:37)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:144:20

**Comment by dteviot** [comment]
@jillybeans  

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my records: 50 minutes

**Comment by dteviot** [comment]
@jillybeans Updated version (0.0.0.140) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
