### ISSUE TITLE
Not working for mtlnation.com

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#615]
mtlnation.com 
TypeError: Cannot read properties of null (reading 'querySelectorAll') 
at MadaraParser.findContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MadaraParser.js:39:30) 
at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:490:38 at async Promise.all (index 2) 
at async MadaraParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17)

(reported by markleslie catameo)

**Comment by MarkleslieCatameo** [comment]
thank you

**Comment by MarkleslieCatameo** [comment]
remove <div style="display:none;"> content </div> using sigil find/replace
or using your epubeditor
