### ISSUE TITLE
hostednovel.com does not work again

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#617]
Hello

I tried to download a [novel ](https://hostednovel.com/8/novel/little-tyrant-doesnt-want-to-meet-with-a-bad-end)on HostedNovel, but it didn't work : 

```
TypeError: Cannot read properties of null (reading 'src')
    at HostednovelParser.findCoverImageUrl (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/parsers/HostednovelParser.js:47:64)
    at HostednovelParser.populateUI (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/Parser.js:143:29)
    at processInitialHtml (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/main.js:45:24)
    at populateControlsWithDom (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/main.js:222:9)
    at onMessageListener (chrome-extension://nfieoopohpanebeapmaipkbiichknpcb/js/main.js:16:13)
```
I have the 0.0.0.141 version, on Chrome.

Thank you in advance

**Comment by dteviot** [comment]
@Flwk 
URL of Table to Contents which isn't working?

**Comment by dteviot** [comment]
@Flwk
Updated version (0.0.0.141) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested against https://hostednovel.com/8/novel/little-tyrant-doesnt-want-to-meet-with-a-bad-end
For my notes: time taken 70 minutes.  (Submitting to stores and notifying people of updates takes a while.)

**Comment by dteviot** [comment]
@Flwk 
Updated version (0.0.0.142) with mtlnation disabled has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
