### ISSUE TITLE
mtlnation.com not working Again!!!!!

### ISSUE THREAD

**Issue by MarkleslieCatameo** [dteviot/WebToEpub#625]
TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at MtlnationParser.findContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MadaraParser.js:39:30)
    at MtlnationParser.findContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MtlnationParser.js:21:22)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:490:38
    at async Promise.all (index 1)
    at async MtlnationParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17)

Thw
[WebToEpub0.0.0.141.Chrome.zip](https://github.com/dteviot/WebToEpub/files/7445797/WebToEpub0.0.0.141.Chrome.zip)

is Not working too !!!!!!!!!

**Comment by dteviot** [comment]
@MarkleslieCatameo 
Site owner has asked for support to be removed.
https://github.com/dteviot/WebToEpub/issues/624
