### ISSUE TITLE
mtlnation.com error

### ISSUE THREAD

**Issue by Dlordload** [dteviot/WebToEpub#626]
any novel on mtlnation.com has this error

TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at MtlnationParser.findContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MadaraParser.js:39:30)
    at MtlnationParser.findContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MtlnationParser.js:21:22)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:490:38
    at async Promise.all (index 0)
    at async MtlnationParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17)

**Comment by dteviot** [comment]
@Dlordload 
Site owner has asked for support to be removed.
https://github.com/dteviot/WebToEpub/issues/624
