### ISSUE TITLE
Can you add "WIX" websites?

### ISSUE THREAD

**Issue by aelementj** [dteviot/WebToEpub#753]
Specifically this one: [https://rd-mtl.wixsite.com/rdmtl/inside-the-cave-of-obscenity](https://rd-mtl.wixsite.com/rdmtl/inside-the-cave-of-obscenity)(its an **ero-novel** btw)

When i use WebtoEpub, it shows: 
_TypeError: Cannot read properties of undefined (reading 'pageList')
    at WixParser.extractRestUrlsFromJson (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/WixParser.js:42:29)
    at WixParser.buildMapOfPageUrltoRestUrlWithContent (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/WixParser.js:28:21)
    at WixParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/WixParser.js:20:41)
    at WixParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:378:14)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:46:24)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:222:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)_

**Comment by dteviot** [comment]
@aelementj 
Short answer, no, I'm not willing to do https://rd-mtl.wixsite.com.  It's a single story, and trying to parse it is difficult.  (The element IDs are different for every chapter.)  Also, the content for later chapters has moved to blogspot.

The good news is, all chapters (except for very latest) can be found at https://www.lightnovelpub.com/novel/inside-the-cave-of-obscenity
Also, it looks like chapters 4 onward moved from wixsite to https://rd-mtl.blogspot.com/p/inside-cave-of-obscenity.html 
**Warning, if you use the Blogspot ToC, the links for chapters 1 to 3 go to wixsite, and won't work with WebToEpub.**

For my notes: 39 minutes
