### ISSUE TITLE
panda-novel suddenly not working

### ISSUE THREAD

**Issue by Displayeddd** [dteviot/WebToEpub#780]
It was working perfectly this morning but when I tried to use it in the evening, it didn't work and said 

"Error: Fetch of URL 'https://www.panda-novel.com/api/book/chapters/1461/1' failed with network error 403.
    at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:32:25)
    at HttpClient.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:166:45)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:160:31
    at async PandaNovelParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/PandaNovelParser.js:16:32)"

**Comment by Flwk** [comment]
Here is an example : https://www.panda-novel.com/details/sin-system-demonic-harem-after-reincarnation(AN)-1456

I also have this error : 

<html>
<body>


OK
--
Error: Fetch of URL 'https://www.panda-novel.com/api/book/chapters/1456/1' failed with network error 403.     at FetchErrorHandler.onResponseError (chrome-extension://lbndbabjdeplnacojalgijcgejdmiaha/js/HttpClient.js:32:25)     at HttpClient.checkResponseAndGetData (chrome-extension://lbndbabjdeplnacojalgijcgejdmiaha/js/HttpClient.js:166:45)     at chrome-extension://lbndbabjdeplnacojalgijcgejdmiaha/js/HttpClient.js:160:31     at async PandaNovelParser.getChapterUrls (chrome-extension://lbndbabjdeplnacojalgijcgejdmiaha/js/parsers/PandaNovelParser.js:16:32)


</body>
</html>

Thank you very much ! :)

**Comment by dteviot** [comment]
@Flwk @Displayeddd 
I just tried https://www.panda-novel.com/details/sin-system-demonic-harem-after-reincarnation(AN)-1456, and it worked for me.

Note that error 403 is "Forbidden".
> the server understands the request but refuses to authorize it.
  
I usually see this in one of 2 cases.
1. You're trying to fetch paid content, and you haven't paid.
2. Site has decided you're a bot, and is denying access.  Usually for one of 2 reasons.
   2.1 You've been downloading too much, too fast and the site is suspicious, or
   2.2 Site has changed its logic and it now recognizes WebToEpub.

As it's not 1 for that link, and I can download content, it's probably not 2.2 (although they might be in process of rolling out 2.2, and I just haven't run into it yet.)

Things to try.
1. Can you view the chapter normally in the web browser?  If not, it's probably 2.1.  If a CAPTCHA appears and you solve it, things might work again
2. Wait a week for your ISP to change your IP, or site to forget you.

**Comment by Displayeddd** [comment]
It seems to be working again for me. I think it was 2.1.

**Comment by nandakishore2009** [comment]
Attaching the fix 
https://github.com/dteviot/WebToEpub/issues/784#issuecomment-1207467818

**Comment by MrGnut** [comment]
**everything works, but no content**
![tie](https://user-images.githubusercontent.com/89574281/184798534-371bedde-d2bd-48ce-9f3e-66b4c6513346.png)

**Comment by nandakishore2009** [comment]
After replacing the parser PandaNovelParser.js with my fix, it working for me.
Sample Novel: https://www.panda-novel.com/details/my-three-wives-are-beautiful-vampires-(RRN)-1107
<img width="946" alt="image" src="https://user-images.githubusercontent.com/24523188/185786957-782dce53-6c44-44a5-86f0-47b366ea79a9.png">
<img width="959" alt="image" src="https://user-images.githubusercontent.com/24523188/185786972-94556799-ad4f-4c1e-9a70-f6a38b47af1c.png">

**Comment by unOmni** [comment]
Now it is back to not working again except differently this time.
![image](https://user-images.githubusercontent.com/106206117/187051970-b27ec77f-60c3-452f-afea-aea252f34bac.png)
