### ISSUE TITLE
novelhi not working

### ISSUE THREAD

**Issue by Iadders** [dteviot/WebToEpub#788]
Gives the error:

Error: Fetch of URL 'null' failed with network error Failed to fetch.
    at FetchErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:28:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:158:45
    at async NovelhiParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/NovelhiParser.js:12:23)

**Comment by Iadders** [comment]
It looks like they hide the chapter link URLs from the index somehow.

**Comment by Iadders** [comment]
nvm I got it working.
