### ISSUE TITLE
Issue with 69shu parser

### ISSUE THREAD

**Issue by hdloader11** [dteviot/WebToEpub#910]
**Describe the bug**
When I try to use webtoepub to extract chapters from 69shu.com, I get a parser error. Error can be seen below:

TypeError: Cannot read properties of null (reading 'textContent')
    at ShuParser.extractTitleImpl (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/69shuParser.js:22:52)
    at ShuParser.extractTitle (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:216:26)
    at ShuParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:270:31)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:42:39)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:237:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

It also seems like the extension doesn't support Chinese characters, as after I remove the parser manually and load it into chrome, output is scrambled.

**To Reproduce**
1. Go any novel's page on 69shu.com, I've used https://www.69shu.com/43659/ for this
2. Click on webtoepub chrome extension
3. See error

**Expected behavior**
I should be able to extract the chapters for a new epub based on the pre-existing parser, or set my own parameters if the parser is unavailable.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 109.0.5414.120, also tested on latest Firefox build

**Comment by dteviot** [comment]
@hdloader11 
Try from https://www.69shu.com/txt/43659.htm

**Comment by hdloader11** [comment]
Thanks a lot, it's working when ran from the main novel page.
