### ISSUE TITLE
Royalroad.com no longer working

### ISSUE THREAD

**Issue by Cronan1897** [dteviot/WebToEpub#931]
Whenever I try to use WebToEpub on a royalroad fic, this is what I get

TypeError: Cannot read properties of null (reading 'textContent')
    at RoyalRoadParser.extractDescription (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/RoyalRoadParser.js:98:65)
    at RoyalRoadParser.getEpubMetaInfo (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:275:37)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:42:39)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:237:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

Not sure how to fix

**Comment by gamebeaker** [comment]
Duplicate from #930.

**Comment by Cronan1897** [comment]
> Duplicate from #930.

Okay. sorry, how do i delete?

**Comment by gamebeaker** [comment]
@Cronan1897 you can read it here [Closing an issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/closing-an-issue).

**Comment by Zewalla** [comment]
> > Duplicate from #930.
> 
> Okay. sorry, how do i delete?
> 
> I only started using GitHub today

The button you are looking for is right next to the comment button:
![image](https://user-images.githubusercontent.com/126287152/221360686-cd7ad36d-96a4-41a4-b8bf-ceaa1c2c1a34.png)
See that "close issue" with dropdown arrow?
