### ISSUE TITLE
Hostednovel.com bug

### ISSUE THREAD

**Issue by hdloader11** [dteviot/WebToEpub#948]
**Describe the bug**
Most of the novels in hostednovel.com can be downloaded reliably, however for some reason Martial Cultivator novel is giving out the below error:

TypeError: Cannot read properties of undefined (reading 'href')
    at HostednovelParser.extractTocPageUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/HostednovelParser.js:22:40)
    at HostednovelParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/HostednovelParser.js:11:35)
    at HostednovelParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:378:14)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:47:24)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:252:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**To Reproduce**
1. Go to https://hostednovel.com/novel/martial-cultivator
2. Click on the webtoepub extension icon
3. Get the aforementioned error

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 111.0.5563.111

**Comment by dteviot** [comment]
@hdloader11 

D'oh!  Problem with stories where ToC is only a single page.
Should be fixed now.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://hostednovel.com/novel/martial-cultivator

For my notes: 27 minutes work.  (Partly due to GitHub changing their SSH Host key)

**Comment by dteviot** [comment]
@hdloader11 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
