### ISSUE TITLE
Can't download from quotev

### ISSUE THREAD

**Issue by kolbdog3333** [dteviot/WebToEpub#957]
Can't get fanfics from the site.
 Here is the link for one of the stories. 
https://www.quotev.com/story/15662078/The-Iron-Mages/1
Here is the error code:
TypeError: Cannot read properties of null (reading 'querySelectorAll')
    at QuotevParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/QuotevParser.js:16:27)
    at QuotevParser.onLoadFirstPage (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:378:14)
    at processInitialHtml (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:47:24)
    at populateControlsWithDom (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:252:9)
    at onMessageListener (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:16:13)

**Comment by dteviot** [comment]
@kolbdog3333 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.quotev.com/story/15514619/The-List-of-Triangles-Sokeefe/1 chapters 1 to 4
* https://www.quotev.com/story/15662078/The-Iron-Mages/1 (only has 1 chapter)

For my notes: 20 minutes work

**Comment by dteviot** [comment]
@kolbdog3333 

Updated version (0.0.0.154) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
