### ISSUE TITLE
https://www.pawread.com

### ISSUE THREAD

**Issue by Dongboy69** [dteviot/WebToEpub#999]

**Comment by Dongboy69** [comment]
Error: Fetch of URL 'https://www.pawread.com32296' failed with network error Failed to fetch.
    at FetchErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:28:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:177:45
    at async ParserFactory.assignParserToPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/ParserFactory.js:159:32)
    at async ParserFactory.addParsersToPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/ParserFactory.js:151:13)
    at async PawreadParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:464:9)

**Comment by Dongboy69** [comment]
on firefox this error
Fetch of URL 'https://www.pawread.com32296' failed with network error NetworkError when attempting to fetch resource.. onFetchError@moz-extension://81e72f9c-9fe7-4aa5-bd6a-3e5587806d9e/js/HttpClient.js:28:31
wrapFetchImpl/<@moz-extension://81e72f9c-9fe7-4aa5-bd6a-3e5587806d9e/js/HttpClient.js:177:45

**Comment by Dongboy69** [comment]
its getting wrong url i think i tried to manual change url on edit url i was able to download

**Comment by dteviot** [comment]
@Dongboy69 
As you suspect, the Table to Contents has the wrong URL for a chapter.  Not much WebToEpub can do about that.  You'd need to manually fix it.  (Or tell site owners they've got an error.)
